/**
 * @file ui_Screen1.c
 * @brief Screen 1 UI orchestration for the SquareLine Studio-generated layout.
 *
 * @ingroup UI
 *
 * Initializes the screen-specific UI modules and runs the periodic update task
 * that refreshes the shared LVGL objects.
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
// Original files was generated, it has now since been modified, split apart and currently relies on manual maintenance on updates
// TODO - streamline/guide for this?

#include "../ui.h"
#include "../Tabs/Wifi/WiFi_UI.h"
#include "../Tabs/Home/Sensor_UI.h"
#include "../Tabs/Electricity/Electricity_UI.h"
#include "../Tabs/Electricity/Price_UI.h"
#include "../Tabs/Weather/Weather_UI.h"
#include "../Tabs/Settings/Settings_UI.h"
#include "../../main/LEOP/LEOP_Fetcher.h"



static const char *TAG = "UI";

/**
 * @brief Updates the LEOP connection label from the status queue.
 *
 * Consumes at most one queued status message per call and updates the label
 * text and color when the shared UI objects are available.
 */
static void LEOP_UI_Update(void)
{
    if (leop_status_queue == NULL || ui_LEOP_Connected_Label == NULL)
    {
        return;
    }

    leop_status_message_t message;
    if (xQueueReceive(leop_status_queue, &message, 0) != pdPASS)
    {
        return;
    }

    const char *text = "Checking...";
    lv_color_t color = lv_color_hex(0xFFFF00);

    switch (message.state)
    {
    case LEOP_CONNECTION_NO_WIFI:
        text = "No WiFi";
        color = lv_color_hex(0xFF0000);
        break;
    case LEOP_CONNECTION_CHECKING:
        text = "Checking...";
        color = lv_color_hex(0xFFFF00);
        break;
    case LEOP_CONNECTION_CONNECTED:
        text = "Connected";
        color = lv_color_hex(0x00FF07);
        break;
    case LEOP_CONNECTION_DEGRADED:
        text = "Degraded";
        color = lv_color_hex(0xFFA500);
        break;
    case LEOP_CONNECTION_UNAVAILABLE:
        text = "Not connected";
        color = lv_color_hex(0xFF0000);
        break;
    default:
        break;
    }

    lv_label_set_text(ui_LEOP_Connected_Label, text);
    lv_obj_set_style_text_color(ui_LEOP_Connected_Label,
                                color,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
}

/**
 * @brief Background UI update task for Screen 1.
 *
 * Runs in task context, takes the LVGL port lock before updating shared UI
 * objects, and delays between refresh cycles.
 *
 * @param arg Task argument cast to app_state_t * passed from the task creator.
 *
 * @note The update helpers are called while the LVGL port lock is held.
 */
void ui_update_task(void *arg)
{
    app_state_t *app = (app_state_t *)arg;
    while (1)
    {
        if (lvgl_port_lock(pdMS_TO_TICKS(100)))
        {
            WiFi_UI_Update();
            Sensor_UI_Update();
            Electricity_UI_Update();
            Weather_UI_Update_test();
            Price_UI_Update();
            Settings_UI_Update(app);
            LEOP_UI_Update();

            lvgl_port_unlock();
        }
        vTaskDelay(pdMS_TO_TICKS(50));
    }
}

/**
 * @brief Initializes the Screen 1 UI modules.
 *
 * Creates the shared screen content and the tab-specific UI elements used by
 * the generated layout.
 */
void ui_Screen1_screen_init(void)
{

    Main_UI_Initialize();

    Settings_UI_Initialize();

    WiFi_UI_Initialize();

    Sensor_UI_Initialize();

    Electricity_UI_Initialize();

    Price_UI_Initialize();

    weather_dashboard_create();

}

/**
 * @brief Destroys the Screen 1 UI objects.
 */
void ui_Screen1_screen_destroy(void)
{

}
